export { default as Navigation } from './Navigation'
export { default as Home} from './Home'
export { default as Register} from './Register'
export { default as Login} from './Login'
export { default as Posts} from './Posts'